stages:
  - build
  - package

build:
  image: node:lts
  stage: build
  script: 
  - cd web && yarn && REACT_APP_API_ADDRESS_OVERRIDE=http://magento-java-proxy yarn run build:staging
  artifacts:
    paths:
    - web/build
  tags: 
  - docker

.docker_build_tmpl: &docker_build_tmpl
  stage: package
  script:
  - docker build -f ${DOCKERFILE_PATH} -t 939023048332.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${CI_COMMIT_SHORT_SHA} .
  - docker push 939023048332.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${CI_COMMIT_SHORT_SHA}
  - docker rmi 939023048332.dkr.ecr.us-east-1.amazonaws.com/${REPOSITORY}:${CI_COMMIT_SHORT_SHA}

package-tokenserver:
  <<: *docker_build_tmpl
  variables:
    REPOSITORY: 'gfashion/frontend'
    DOCKERFILE_PATH: 'docker/frontend/Dockerfile'
  tags: 
  - docker
