swagger: "2.0"
info:
  description: "GFashion"
  version: "1.0.0"
  title: "GFashion"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "gtv1.org"
basePath: "/v1"
tags:
  - name: "gfashion"
    description: "Everything about GFashion"
  - name: "order"
    description: "Access to GFashion Store orders"
  - name: "cart"
    description: "Access to user's cart"
  - name: "user"
    description: "Operations about user"
  - name: "product"
    description: "Recommended product"
  - name: "designer"
    description: "Recommended desginer"
schemes:
  - "https"
  - "http"
paths:
  /product:
    post:
      tags:
        - "product"
      summary: "Add a new product to the store"
      description: ""
      operationId: "addProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
    put:
      tags:
        - "product"
      summary: "Update an existing product"
      description: ""
      operationId: "updateProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/search:
    get:
      tags:
        - "product"
      summary: "Searches Products by given query string"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "searchProducts"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/{productId}:
    get:
      tags:
        - "product"
      summary: "Find product by ID"
      description: "Returns a single product"
      operationId: "getProdutById"
      security:
        - api_key: []
    post:
      tags:
        - "product"
      summary: "Updates a product in the store with form data"
      description: ""
      operationId: "updateProductWithForm"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
    delete:
      tags:
        - "product"
      summary: "Deletes a product"
      description: ""
      operationId: "deleteProduct"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"
  /product/{productId}/uploadImage:
    post:
      tags:
        - "product"
      summary: "uploads an image"
      description: ""
      operationId: "uploadProductFile"
      security:
        - gfashionstore_auth:
            - "write:products"
            - "read:products"

  /order:
    post:
      tags:
        - "order"
      summary: "Place an order for a product"
      description: ""
      operationId: "placeOrder"
  /order/{orderId}:
    get:
      tags:
        - "order"
      summary: "Find purchase order by ID"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getOrderById"
    delete:
      tags:
        - "order"
      summary: "Delete purchase order by ID"
      description: "For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors"
      operationId: "deleteOrder"
  /order/ordersofuser/{userId}:
    get:
      tags:
        - "order"
      summary: "Find purchase orders by UserId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getOrdersByUserId"
  /cart/{userId}:
    get:
      tags:
        - "cart"
      summary: "Find all items in the shopping cart by userId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "getItemsinCartByUserId"
  /cart/{userId}/{productId}:
    delete:
      tags:
        - "cart"
      summary: "Delete item in cart by UserId"
      description: "For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors"
      operationId: "deleteItemInCart"
  /cart/addto/{userId}/cart/{productId}:
    post:
      tags:
        - "cart"
      summary: "Add an item to the shopping cart of a user with userId"
      description: "For valid response try integer IDs with value >= 1 and <= 10. Other values will generate exceptions"
      operationId: "addItemtoCartByUserId"
  /user:
    post:
      tags:
        - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
  /user/createWithArray:
    post:
      tags:
        - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithArrayInput"
  /user/createWithList:
    post:
      tags:
        - "user"
      summary: "Creates list of users with given input array"
      description: ""
      operationId: "createUsersWithListInput"
  /user/login:
    get:
      tags:
        - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
  /user/logout:
    get:
      tags:
        - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
  /user/{username}:
    get:
      tags:
        - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
    put:
      tags:
        - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
    delete:
      tags:
        - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
  /designer:
    post:
      tags:
        - "designer"
      summary: "Add a new designer to the store"
      description: ""
      operationId: "adddesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
    put:
      tags:
        - "designer"
      summary: "Update an existing designer"
      description: ""
      operationId: "updatedesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designer/search:
    get:
      tags:
        - "designer"
      summary: "Searches designers by given query string"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "searchdesigners"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designer/{designerId}:
    get:
      tags:
        - "designer"
      summary: "Find designer by ID"
      description: "Returns a single designer"
      operationId: "getDesignerById"
      security:
        - api_key: []
    post:
      tags:
        - "designer"
      summary: "Updates a designer in the store with form data"
      description: ""
      operationId: "updatedesignerWithForm"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
    delete:
      tags:
        - "designer"
      summary: "Deletes a designer"
      description: ""
      operationId: "deletedesigner"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"
  /designer/{designerId}/uploadImage:
    post:
      tags:
        - "designer"
      summary: "uploads an image"
      description: ""
      operationId: "uploadDesignerFile"
      security:
        - gfashionstore_auth:
            - "write:designers"
            - "read:designers"

securityDefinitions:
  gfashionstore_auth:
    type: "oauth2"
    authorizationUrl: "http://gfashionstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:products: "modify products in your account"
      read:products: "read your products"
      write:designers: "modify designers in your account"
      read:designers: "read your designers"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"