import React from 'react';
import './App.css';
import CssBaseline from '@material-ui/core/CssBaseline';
import useMediaQuery from '@material-ui/core/useMediaQuery';
import { createMuiTheme, ThemeProvider } from '@material-ui/core/styles';

import AppRouter from './routers/AppRouter';

function App() {
  const isDarkModePrefered = useMediaQuery('(prefers-color-scheme: dark)');

  const theme = React.useMemo(() =>
    createMuiTheme({
      palette: {
        primary: {
          // light : specify or auto-generated by main color
          main: '#2196f3',
          // dark: specify or auto-generated by main color
        },
        // ... and we will overrides more default colors at here
        type: isDarkModePrefered ? 'dark' : 'light',
      },
    }),
    [isDarkModePrefered]);

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <AppRouter />
    </ThemeProvider>
  );
}

export default App;
