version: "3"
services:

  website:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gf:1.0.0
    environment:
      - REACT_APP_API_ADDRESS_OVERRIDE=http://localhost:5005
    ports:
      - "8081:80"
    restart: always
    networks:
      - gf_frontend_net

networks:
  gf_frontend_net:
